import org.jetbrains.changelog.Changelog

plugins {
    id 'org.jetbrains.kotlin.jvm' version "2.4.10"
    id 'org.jetbrains.intellij.platform' version '2.18.1'
    id 'org.jetbrains.changelog' version '2.5.0'
}

apply plugin: 'org.jetbrains.changelog'

group = 'de.ehmkah.projects'
version = '1.12.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    implementation 'com.squareup:gifencoder:0.10.1'

    intellijPlatform {
        intellijIdea('2026.2')
    }

    testImplementation('org.junit.jupiter:junit-jupiter:6.1.2')
    testImplementation('org.mockito.kotlin:mockito-kotlin:6.3.0')
    testImplementation('org.jetbrains.kotlin:kotlin-test:2.4.10')
}

test {
    useJUnitPlatform()
}

intellijPlatform {
    pluginConfiguration {
        ideaVersion {
            sinceBuild.set('262')
        }
        changeNotes.set(provider({changelog.renderItem(changelog.getLatest(), Changelog.OutputType.HTML)}))
    }
}

changelog {
    version = "1.12.0"
    path = "${project.projectDir}/CHANGELOG.md"
    header = "[${-> version.get()}]}"
    itemPrefix = "-"
    keepUnreleasedSection = true
    unreleasedTerm = "[Unreleased]"
    groups = ["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security"]
}

// Workaround because of https://youtrack.jetbrains.com/issue/KT-42837
buildSearchableOptions.enabled=false
