plugins {
    id 'org.jetbrains.kotlin.jvm' version "2.3.21"
    id 'org.jetbrains.intellij.platform' version '2.14.0'
    id 'org.jetbrains.changelog' version '1.2.1'
}

apply plugin: 'org.jetbrains.changelog'

group = 'de.ehmkah.projects'
version = '1.12.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    implementation 'com.squareup:gifencoder:0.10.1'

    intellijPlatform {
        intellijIdea('2025.3')
    }

    testImplementation('org.junit.jupiter:junit-jupiter:5.7.2')
    testImplementation('org.mockito.kotlin:mockito-kotlin:5.4.0')
    testImplementation('junit:junit:4.13.2')
    testImplementation('org.jetbrains.kotlin:kotlin-test:2.3.21')
}

intellijPlatform {
    pluginConfiguration {
        ideaVersion {
            sinceBuild.set('253')
        }
        changeNotes.set(provider({changelog.getLatest().toHTML()}))
    }
}

changelog {
    version = "1.11.0"
    path = "${project.projectDir}/CHANGELOG.md"
    header = "[${-> version.get()}]}"
    itemPrefix = "-"
    keepUnreleasedSection = true
    unreleasedTerm = "[Unreleased]"
    groups = ["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security"]
}

// Workaround because of https://youtrack.jetbrains.com/issue/KT-42837
buildSearchableOptions.enabled=false
